name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:

  cargo_bloat:
    runs-on: ubuntu-latest
    
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libwayland-dev libdrm-dev libseat-dev libwayland-egl-backend-dev libxkbcommon-dev libxkbcommon-x11-dev
          version: 1.0
      - uses: actions/checkout@master
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run cargo bloat
        uses: orf/cargo-bloat-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
